# 李帅龙（Li Shuailong）个人网站配置
title: Li Shuailong (李帅龙)
description:  PhD MD（主治医师）Neuroscience/Cell Biology/Anaesthetics
author: Li Shuailong
url: https://lishuailong.github.io 
markdown: kramdown
theme: jekyll-theme-minima 
